FlightTicketBooking/FlightTicketBooking/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("tickets.urls")),
]

FlightTicketBooking/tickets/urls.py
from django.urls import path
from . import views

urlpatterns=[
    path('login', views.login, name='login'),
    path('', views.login, name='login'),
    path('register', views.register, name='register'),
    path('profile', views.profile, name='profile'),
    path('adminlogin', views.adminlogin, name='adminlogin'),
    path('addflight', views.addflight, name='addflight'),
    path('removeflight/<int:flight_id>', views.removeflight, name='removeflight'),
    path('adminprofile', views.adminprofile, name='adminprofile'),
    path('logout', views.logout, name='logout'),
    path('bookflight/<int:flight_id>', views.bookflight, name='bookflight'),
    path('buyticket', views.buyticket, name='buyticket'),
    path("verify_email", views.verify_email, name="verify_email"),
    path("adminview", views.adminview, name='adminview'),
]

FlightTicketBooking/tickets/models.py
from django.db import models
from django.contrib.auth.hashers import make_password

# Create your models here.
class User(models.Model):
    id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=100)
    age = models.PositiveIntegerField()
    contactno = models.CharField(max_length=20)
    email = models.CharField(max_length=100, unique=True)
    password = models.CharField(max_length=100)
    token = models.CharField(max_length=32)
    is_verified = models.BooleanField(default=False)

    def __str__(self):
      return self.name
    
    def save(self, *args, **kwargs):
        if not self.password.startswith('pbkdf2_sha256'):
            self.password = make_password(self.password)
        super().save(*args, **kwargs)

class Flight(models.Model):
    flight_number=models.CharField(max_length=100,unique=True)
    flight_name = models.CharField(max_length=100)
    flight_from = models.CharField(max_length=100)
    flight_to = models.CharField(max_length=100)
    takeoff_date = models.DateField()
    arrival_date = models.DateField()
    takeoff_time = models.TimeField()
    arrival_time = models.TimeField()
    flight_duration = models.FloatField()
    number_of_seats = models.IntegerField()
    price = models.IntegerField()
    seats_booked = models.IntegerField()

    def __str__(self):
      return self.flight_number
    
class Flight_Book(models.Model):
   user = models.ForeignKey(User, on_delete=models.CASCADE)
   flight = models.ForeignKey(Flight, on_delete=models.CASCADE)

   def __str__(self):
      return f"{str(self.flight)}, {str(self.user)}"
   

FlightTicketBooking/templates/addflight.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin Profile</title>
    <link rel = "icon" href = "https://cdn-icons-png.flaticon.com/512/3125/3125713.png" type = "image/x-icon">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.4.js" integrity="sha256-a9jBBRygX1Bh5lt8GZjXDzyOB+bWve9EiO7tROUtj/E=" crossorigin="anonymous"></script>
    
</head>
<body>

    <nav class="navbar navbar-dark bg-primary">
      <a class="navbar-brand" href="adminview">
        <img src="https://cdn-icons-png.flaticon.com/512/3125/3125713.png" width="30" height="30" class="d-inline-block align-top" alt="">
        AirDev
        </a>
        <div style="float: right;">
            <a style="color: white; margin:0 25px 0 0" href="/adminview">View Booking Details </a>
            <a style="color: white; margin:0 25px 0 0" href="/adminprofile">Admin Profile</a>
            <a style="color: white;" href="/logout" >Logout</a>
        </div>
    </nav>
    
    <div class="container rounded bg-white mt-5" >
      <div class="mask d-flex align-items-center h-100 gradient-custom-3">
        <div class="container h-100">
          <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-12 col-md-9 col-lg-7 col-xl-6">
              <div class="card" style="border-radius: 15px;">
                <div class="card-body p-5">
                  <h2 class="text-uppercase text-center mb-5">Add Flight</h2>
                  <form class="" method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <div class="d-flex justify-content-center">
                      <input  class="submit btn btn-success btn-block btn-lg gradient-custom-4 text-body" value="Add Flight" type="submit" />
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      
    
       
    </div>


</body>
</html>

FlightTicketBooking/templates/adminlogin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link rel = "icon" href = "https://cdn-icons-png.flaticon.com/512/3125/3125713.png" type = "image/x-icon">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.4.js" integrity="sha256-a9jBBRygX1Bh5lt8GZjXDzyOB+bWve9EiO7tROUtj/E=" crossorigin="anonymous"></script>

</head>
<body>

  <nav class="navbar navbar-dark bg-primary" style="margin-bottom: 30px;">
    <a class="navbar-brand" href="adminview">
    <img src="https://cdn-icons-png.flaticon.com/512/3125/3125713.png" width="30" height="30" class="d-inline-block align-top" alt="">
    AirDev
    </a>
  </nav>
    
    <div class="mask d-flex align-items-center h-100 gradient-custom-3">
        <div class="container h-100">
          <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-12 col-md-9 col-lg-7 col-xl-6">
              <div class="card" style="border-radius: 15px;">
                <div class="card-body p-5">
                  <h2 class="text-uppercase text-center mb-5">Admin Login</h2>

                  
                  <form class="" action="" method="post">
                    {% csrf_token %}

                    <div class="form-outline mb-4">

                      <input type="text" placeholder="Username" name="username" id="username" class="form-control form-control-lg" />
                      
                    </div>
                    <span style="color:red" id="sid"></span>
    
                    <div class="form-outline mb-4">
                      <input type="password" placeholder="Password"  name="password" id="password" class="form-control form-control-lg" />
                      
                    </div>
    
                    <div class="d-flex justify-content-center">
                      <input  class="submit btn btn-success btn-block btn-lg gradient-custom-4 text-body" value="Login" type="submit" />
                      
                    </div>

                  </form>
                    <span style="color:red" id="mesid">
                      {% if show == 1 %}
                      <p>Invalid credentials</p>
                      {% endif %}
                    </span>
    
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
</body>
</html>

FlightTicketBooking/templates/adminprofile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin Profile</title>
    <link rel = "icon" href = "https://cdn-icons-png.flaticon.com/512/3125/3125713.png" type = "image/x-icon">
    {% load static %} 
    <link href="{% static 'main.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.4.js" integrity="sha256-a9jBBRygX1Bh5lt8GZjXDzyOB+bWve9EiO7tROUtj/E=" crossorigin="anonymous"></script>
    
</head>
<body>

    <nav class="navbar navbar-dark bg-primary">
      <a class="navbar-brand" href="adminview">
        <img src="https://cdn-icons-png.flaticon.com/512/3125/3125713.png" width="30" height="30" class="d-inline-block align-top" alt="">
        AirDev
        </a>
        <div style="float: right;">
            <a style="color: white; margin:0 25px 0 0" href="/adminview">View Booking Details </a>
            <a style="color: white; margin:0 25px 0 0" href="/addflight">Add Flights </a>
            <a style="color: white;" href="/logout" >Logout</a>
        </div>
    </nav>
    
    <div class="container rounded bg-white mt-5" >
      {% if flights %}
      <h2 style="text-align:center">Available Flights</h2>
      {% else %}  <h2 style="text-align:center">Sorry! No flights Available</h2> {% endif %}
      {% for flight in flights %}
        <div class="card" style="width: 50%; margin:0 auto">
          <div class="card-body">
            <h5 class="card-title">{{ flight.flight_name }}</h5>
            <h6 class="card-subtitle mb-2 text-muted">Flight Info</h6>
            <ul class="list-group list-group-flush">
              <li class="list-group-item">Flight No. : <b>{{ flight.flight_number }}</b>  </li>
              <li class="list-group-item">From : {{ flight.flight_from }}</li>
              <li class="list-group-item">To : {{ flight.flight_to }} </li>
              <li class="list-group-item">Departure Date : {{ flight.takeoff_date }} </li>
              <li class="list-group-item">Departure Time : {{ flight.takeoff_time }} </li>
              <li class="list-group-item">Arrival Date : {{ flight.arrival_date }} </li>
              <li class="list-group-item">Arrival Time :  {{ flight.arrival_time }} </li>
              <li class="list-group-item">Flight Duration : {{ flight.flight_duration }} hrs</li>
              <li class="list-group-item">Ticket Price : Rs.{{ flight.price }}</li>
              <li class="list-group-item"><form method="post" action="{% url 'removeflight' flight.pk %}">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger">Remove Flight</button>
            </form></li>
              
            </ul>
          </div>
        </div>
        <hr>
      {% endfor %}       
    </div>


</body>
</html>

FlightTicketBooking/templates/adminview.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin Profile</title>
    <link rel = "icon" href = "https://cdn-icons-png.flaticon.com/512/3125/3125713.png" type = "image/x-icon">
    {% load static %} 
    <link href="{% static 'main.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.4.js" integrity="sha256-a9jBBRygX1Bh5lt8GZjXDzyOB+bWve9EiO7tROUtj/E=" crossorigin="anonymous"></script>
    
</head>
<body>

    <nav class="navbar navbar-dark bg-primary">
      <a class="navbar-brand" href="adminview">
        <img src="https://cdn-icons-png.flaticon.com/512/3125/3125713.png" width="30" height="30" class="d-inline-block align-top" alt="">
        AirDev
        </a>
        <div style="float: right;">
            <a style="color: white; margin:0 25px 0 0" href="/adminprofile">Remove Flight Details </a>
            <a style="color: white; margin:0 25px 0 0" href="/addflight">Add Flights </a>
            <a style="color: white;" href="/logout" >Logout</a>
        </div>
    </nav>
    
    <div class="container rounded bg-white mt-5" >
      {% if flights %}
      <h2 style="text-align:center">Flight Details</h2>
      {% else %}  <h2 style="text-align:center">Sorry! No flights Available</h2> {% endif %}
      {% for flight in flights %}
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">{{ flight.flight_name }}</h5>
            <h6 class="card-subtitle mb-2 text-muted">Flight Info</h6>
            <ul class="list-group list-group-flush">
              <li class="list-group-item">Flight No. : <b>{{ flight.flight_number }}</b>  </li>
              <li class="list-group-item">From : {{ flight.flight_from }}</li>
              <li class="list-group-item">To : {{ flight.flight_to }} </li>
              <li class="list-group-item">Departure Date : {{ flight.takeoff_date }} </li>
              <li class="list-group-item">Departure Time : {{ flight.takeoff_time }} </li>
              <li class="list-group-item">Arrival Date : {{ flight.arrival_date }} </li>
              <li class="list-group-item">Arrival Time :  {{ flight.arrival_time }} </li>
              <li class="list-group-item">Flight Duration : {{ flight.flight_duration }} hrs</li>
              <li class="list-group-item">Ticket Price : Rs.{{ flight.price }}</li>
              <li class="list-group-item">
                <h6>Booked List:</h6>
                <ul>
                  {% for booking in flight.flight_book_set.all %}
                      <li>{{ booking.user.name }} - {{ booking.user.email }}</li>
                  {% empty %}
                      <li>No bookings for this flight</li>
                  {% endfor %}
                </ul>
              </li>  
            </ul>
          </div>
        </div>
        <hr>
      {% endfor %}
       
    </div>


</body>
</html>

FlightTicketBooking/templates/buyticket.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Buy Tickets</title>
    <link rel = "icon" href = "https://cdn-icons-png.flaticon.com/512/3125/3125713.png" type = "image/x-icon">
    {% load static %} 
    <link href="{% static 'main.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.4.js" integrity="sha256-a9jBBRygX1Bh5lt8GZjXDzyOB+bWve9EiO7tROUtj/E=" crossorigin="anonymous"></script>
    
</head>
<body>

    <nav class="navbar navbar-dark bg-primary">
      <a class="navbar-brand" href="profile">
        <img src="https://cdn-icons-png.flaticon.com/512/3125/3125713.png" width="30" height="30" class="d-inline-block align-top" alt="">
        AirDev
        </a>
        <div style="float: right;">
            <a style="color: white; margin:0 25px 0 0" href="/profile">Profile</a>
            <a style="color: white;" href="/logout">Logout</a>
        </div>
    </nav>
    <br>

    <form method="get" action="">

    <div class="form-row">
      <div class="col">
        <label for="date-greater" style="font-family:'Times New Roman', Times, serif">Date Greater than:</label>
        <input class="form-control" type="date" id="date-greater" name="date_greater" value="{{date_greater}}">
      </div>
      <div class="col">
        <label for="date-less" style="font-family:'Times New Roman', Times, serif">Date Less than:</label>
        <input class="form-control" type="date" id="date-less" name="date_less" value="{{date_lesser}}">
      </div>
      <div class="col">
        <label for="time-greater" style="font-family:'Times New Roman', Times, serif">Time Greater than:</label>
        <input class="form-control" type="time" id="time-greater" name="time_greater" value="{{time_greater}}">
      </div>
      <div class="col">
        <label for="time-less" style="font-family:'Times New Roman', Times, serif">Time Less than:</label>
        <input type="time" class="form-control"  id="time-less" name="time_less" value="{{time_lesser}}">
      </div>
      <div class="col">
        
        <button type="submit" id="btn"class="btn btn-info" style="margin-top: 32px;">Apply Filters</button>
      </div>
    </div>
    
    </form>
    <div class="container rounded bg-white mt-5" >
      {% if flights %}
      <h2 style="text-align:center">Available Flights</h2>
      {% else %}  <h2 style="text-align:center">Sorry! No flights Available</h2> {% endif %}
      {% for flight in flights %}
        <div class="card" style="width: 65%;margin:0 auto;">
          <div class="card-body">
            <h5 class="card-title">{{ flight.flight_name }}</h5>
            <h6 class="card-subtitle mb-2 text-muted">Flight Info</h6>
            <ul class="list-group list-group-flush">
              <li class="list-group-item">Flight No. : <b>{{ flight.flight_number }}</b>  </li>
              <li class="list-group-item">From : {{ flight.flight_from }}</li>
              <li class="list-group-item">To : {{ flight.flight_to }} </li>
              <li class="list-group-item">Departure Date : {{ flight.takeoff_date }} </li>
              <li class="list-group-item">Departure Time : {{ flight.takeoff_time }} </li>
              <li class="list-group-item">Arrival Date : {{ flight.arrival_date }} </li>
              <li class="list-group-item">Arrival Time :  {{ flight.arrival_time }} </li>
              <li class="list-group-item">Flight Duration : {{ flight.flight_duration }} hrs</li>
              <li class="list-group-item">Ticket Price : Rs.{{ flight.price }}</li>
              <li class="list-group-item"><form method="post" action="{% url 'bookflight' flight.pk %}">
                {% csrf_token %}
                <button type="submit" class="btn btn-success">Book Ticket</button>
                 </form>
              </li>
              
            </ul>
          </div>
        </div>
        <hr>
      {% endfor %}
       
    </div>


</body>
</html>

FlightTicketBooking/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link rel = "icon" href = "https://cdn-icons-png.flaticon.com/512/3125/3125713.png" type = "image/x-icon">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.4.js" integrity="sha256-a9jBBRygX1Bh5lt8GZjXDzyOB+bWve9EiO7tROUtj/E=" crossorigin="anonymous"></script>

</head>
<body>

  <nav class="navbar navbar-dark bg-primary" style="margin-bottom: 30px;">
    <a class="navbar-brand" href="profile">
    <img src="https://cdn-icons-png.flaticon.com/512/3125/3125713.png" width="30" height="30" class="d-inline-block align-top" alt="">
    AirDev
    </a>
    <div style="float: right;">
      <a style="color: white; margin:0 25px 0 0" href="/adminlogin">Admin</a>
    </div>
  </nav>
    
    <div class="mask d-flex align-items-center h-100 gradient-custom-3">
        <div class="container h-100">
          <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-12 col-md-9 col-lg-7 col-xl-6">
              <div class="card" style="border-radius: 15px;">
                <div class="card-body p-5">
                  <h2 class="text-uppercase text-center mb-5">Login</h2>

                  
                  <form class="" action="" method="post">
                    {% csrf_token %}

                    <div class="form-outline mb-4">

                      <input type="email" placeholder="Email" name="email" id="email" class="form-control form-control-lg" />
                      
                    </div>
                    <span style="color:red" id="sid"></span>
    
                    <div class="form-outline mb-4">
                      <input type="password" placeholder="Password"  name="password" id="password" class="form-control form-control-lg" />
                      
                    </div>
    
                    <div class="d-flex justify-content-center">
                      <input  class="submit btn btn-success btn-block btn-lg gradient-custom-4 text-body" value="Login" type="submit" />
                    </div>

                  </form>
                    <span style="color:red" id="mesid">
                      {% if show == 1 %}
                      <p>Invalid credentials or Mail not verified yet</p>
                      {% endif %}
                    </span>
    
                    <p class="text-center text-muted mt-5 mb-0">Don't you already have an account? <a href="/register"
                        class="fw-bold text-body"><u>Register here</u></a></p>
    
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
</body>
</html>